/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practicatabla;

import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Principal
        extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        Lista l = new Lista();
        l.agregarNodo(15);
        l.agregarNodo(5);
        l.agregarNodo(52);
        l.agregarNodo(8);
        l.agregarNodo(75);
        l.agregarNodo(33);
        l.agregarNodo(25);
        l.agregarNodo(3);
        l.agregarNodo(74);
        l.agregarNodo(18);
        l.agregarNodo(20);
        int arregloNodos[] = new int [l.getCantidadN()];
        arregloNodos = l.imprimirLista2();
        DefaultTableModel modelo = new DefaultTableModel();
        String[] cabecera = {"Nodos", "ALfa", "Beta"};
        modelo.setColumnIdentifiers(cabecera);
        Object[] datos = new Object[l.getCantidadN()];
        for(int i = 0; i<l.getCantidadN(); i++){
            datos[0] = arregloNodos[i];
            datos[1] = "a";
            datos[2] = "b";
            modelo.addRow(datos);
        }
        jtListado.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtListado = new javax.swing.JTable();
        jbnPersonas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtListado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtListado);

        jbnPersonas.setText("Listado de Personas");
        jbnPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnPersonasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbnPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbnPersonas)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnPersonasActionPerformed
       Persona[] arregloP = new Persona[5];
       for(int i = 0; i<5; i++){
           arregloP[i] = new Persona(null,
                   null,
                   0);
       }
       arregloP[0] = new Persona("Ana", "Jimenez", 18);
       arregloP[1] = new Persona("Ivan", "Ramirez", 21);
       arregloP[2] = new Persona("Chuy", "Lopez", 19);
       arregloP[3] = new Persona("Andy", "Jimenez", 22);
       arregloP[4] = new Persona("Carlos", "Zuñiga", 23);
       DefaultTableModel modeloPersona = new DefaultTableModel();
       String[] encabezado = {"No.", "Nombre", "Apellidos", "Edad"};
       modeloPersona.setColumnIdentifiers(encabezado);
       Object[] datosPersona = new Object[arregloP.length];
       for(int i= 0; i<arregloP.length; i++){
           datosPersona[0] = i+1;
           datosPersona[1] = arregloP[i].getNombre();
           datosPersona[2] = arregloP[i].getApelluido();
           datosPersona[3] = arregloP[i].getEdad();
           modeloPersona.addRow(datosPersona);
       }
        jtListado.setModel(modeloPersona);
        
    }//GEN-LAST:event_jbnPersonasActionPerformed

    private void jtListadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListadoMouseClicked
        int numRenglon = jtListado.getSelectedRow();
        int numColumna = jtListado.getSelectedColumn();
        String valor = jtListado.getValueAt(numRenglon,
                numColumna).toString();
        JOptionPane.showMessageDialog(null, "Valor:" + valor + "\n" + "Renglon/Columna:" + numRenglon + "," + numColumna);
    }//GEN-LAST:event_jtListadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
                    getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbnPersonas;
    private javax.swing.JTable jtListado;
    // End of variables declaration//GEN-END:variables
}
